# Generated by Django 5.0.1 on 2024-05-06 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocawishlistmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='link',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wishlists',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
