# Generated by Django 5.0.1 on 2024-05-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocawishlistmaker', '0002_items_link_alter_items_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(),
        ),
    ]
