# Generated by Django 5.0.1 on 2024-06-14 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocawishlistmaker', '0004_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
