# Generated by Django 5.0.1 on 2024-06-15 00:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocawishlistmaker', '0007_remove_urls_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLs',
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
