# Generated by Django 5.0.1 on 2024-06-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pocawishlistmaker', '0012_wishlists_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='name',
        ),
    ]
