# Generated by Django 5.0.1 on 2024-06-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocawishlistmaker', '0013_rename_tag_tags_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlists',
            name='tags',
            field=models.ManyToManyField(to='pocawishlistmaker.tags'),
        ),
    ]
